apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: weather-api
  namespace: mi-namespace
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: weather-api
  minReplicas: 1
  maxReplicas: 2
