apiVersion: v1
kind: Service
metadata:
  name: weather-api
  namespace: mi-namespace
spec:
  type: LoadBalancer
  selector:
    app: weather-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
